version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/lightcode/main.go
    binary: lightcode
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "lightcode_{{.Version}}_{{.Os}}_{{.Arch}}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "lightcode_{{.Version}}_checksums.txt"

release:
  github:
    owner: Kartik-2239
    name: lightcode